### ISSUE TITLE
請問我還是不懂怎麼讓機器人上線可以再說明清楚一點嗎?

### ISSUE THREAD

**Issue by Danielliou1689** [B-l-u-e-b-e-r-r-y/Discord-Bot-01#1]

**Comment by B-l-u-e-b-e-r-r-y** [comment]
請告訴我你在哪個步驟遇到問題，這樣我才會知道你卡在哪邊
或是這邊有其他人製作的教學影片，影片比較容易照著做：[【Discord.JS】8分鐘內簡單創建Discord機器人!
](https://www.youtube.com/watch?v=Ak_bU1ecL7I&ab_channel=%E8%8B%A6%E5%8A%9B%E6%80%95%E6%80%95JIM)
